#!/bin/bash

INSTALLED_DIR=/usr/share/grubfix

patch -uNr - /etc/grub.d/00_header $INSTALLED_DIR/00_header.patch
update-grub

# After executing once from inside /etc, remove the symlink.
SCRIPT_PATH=$0
if [[ $SCRIPT_PATH == /etc/* ]]; then
    rm "$SCRIPT_PATH"
fi
