#!/bin/bash

CURRENT_NAME=$(hostname)
if [ $# -eq 1 ]; then
  NEW_NAME=$1
else
  echo "Please enter a new name for $CURRENT_NAME: "
  read NEW_NAME
  if [ -z "$NEW_NAME" ]; then
    echo "Nothing entered, no change."
    exit 1
  fi
fi

echo "Changing name $CURRENT_NAME to $NEW_NAME."

sudo sed -i "s/$CURRENT_NAME/$NEW_NAME/g" /etc/host*
sudo sed -i "s/$CURRENT_NAME/$NEW_NAME/g" /etc/wicd/wireless-settings.conf

echo "Initiating system restart to complete name change."
sleep 2

sudo shutdown -r now
